import type { IndustryContent } from "@/components/public/templates/industryPage";

export const INDUSTRIES: Record<string, IndustryContent> = {
  education: {
    slug: "education",
    name: "Education",
    noun: "education",
    heroImage: "/images/unsplash/photo-1503676260728-1c00da094a0b-1600.webp",
    headline: { lead: "Cloud that's ready when", emph: "campuses", tail: "are." },
    lede: "From K-12 districts to research universities — platforms that scale through enrollment peaks, stay FERPA-aligned, and keep IT teams off the war-room rotation.",
    pills: ["K-12 & higher ed", "FERPA-aligned", "SIS & LMS"],
    challenges: [
      { letter: "A", title: "Seasonal load spikes", body: "Enrollment windows, finals week, course registration — the same systems carry 10× load on the same day." },
      { letter: "B", title: "Identity sprawl across SIS / LMS", body: "Faculty, students, parents, contractors — too many directories, not enough single sign-on." },
      { letter: "C", title: "Data privacy & compliance", body: "FERPA, COPPA, state privacy laws — controls that audit cleanly without slowing teachers down." },
    ],
    approach: [
      { title: "Audit current estate", body: "Inventory SIS, LMS, identity, network — map gaps against sector benchmarks." },
      { title: "Stand up landing zones", body: "Multi-account topology · IAM · network · guardrails for student data." },
      { title: "Migrate & modernize", body: "Lift critical apps in waves · refactor the ones that buckle at peak." },
      { title: "Operate as one team", body: "Embedded SRE through registration season · clean hand-off after." },
    ],
    diagramLabel: "Identity at the front · campus + cloud workloads in the middle · observability and cost visible from the SIS owner's desk.",
    related: [
      { kind: "Service", name: "DevOps & Automation", href: "/services/devops_automation" },
      { kind: "Solution", name: "Hybrid Cloud", href: "/solutions/hybrid_cloud" },
      { kind: "Solution", name: "Security & Compliance", href: "/solutions/security_compliance" },
      { kind: "Service", name: "Staffing Services", href: "/services/staff_augmentation" },
    ],
  },
  finance: {
    slug: "finance",
    name: "Finance",
    noun: "financial services",
    heroImage: "/images/unsplash/photo-1454165804606-c3d57bc86b40-1600.webp",
    headline: { lead: "Speed where the regulator", emph: "expects", tail: "rigor." },
    lede: "Tier-1 banks, payments, and capital markets. We ship inside change-management windows that don't move — and audit trails that don't blink.",
    pills: ["Tier-1 banks", "PCI-DSS", "SOX", "FINRA"],
    challenges: [
      { letter: "A", title: "Change windows that don't flex", body: "Markets open whether your deploy worked or not. Releases need to land in 2-hour windows, with rollback in seconds." },
      { letter: "B", title: "Audit evidence on demand", body: "SOX, PCI, FINRA — auditors want proof, not promises. Evidence has to fall out of the pipeline." },
      { letter: "C", title: "Latency that pays the bills", body: "Single-digit milliseconds on the trading path · double-digit on the customer path. Both, every day." },
    ],
    approach: [
      { title: "Audit current estate", body: "Trading, payments, core banking, data — map by criticality and regulatory exposure." },
      { title: "Stand up landing zones", body: "Segregated environments · network isolation · evidence pipeline live from day one." },
      { title: "Migrate & modernize", body: "Strangler patterns around the mainframe · parallel-run before any cutover." },
      { title: "Operate as one team", body: "24/7 follow-the-sun rotation through market hours · on-call we own." },
    ],
    diagramLabel: "Trading path on one side · audit/evidence on the other · everything labeled, encrypted, and traceable to a control.",
    related: [
      { kind: "Solution", name: "Security & Compliance", href: "/solutions/security_compliance" },
      { kind: "Solution", name: "Enterprise Security", href: "/solutions/enterprise_security" },
      { kind: "Service", name: "Cybersecurity", href: "/services/cybersecurity" },
      { kind: "Solution", name: "Business Continuity", href: "/solutions/business_continuity" },
    ],
  },
  government: {
    slug: "government",
    name: "Government",
    noun: "public sector",
    heroImage: "/images/unsplash/photo-1541872703-74c5e44368f9-1600.webp",
    headline: { lead: "Citizen services that", emph: "actually", tail: "work." },
    lede: "Federal, state, and local — modernization inside procurement reality. FedRAMP, StateRAMP, CJIS · accessibility built in · vendor lock-out avoided.",
    pills: ["FedRAMP", "StateRAMP", "CJIS", "Section 508"],
    challenges: [
      { letter: "A", title: "Procurement gravity", body: "Vehicles, schedules, set-asides — the contracting path shapes the architecture as much as the requirements do." },
      { letter: "B", title: "Authority to Operate", body: "FedRAMP, ATO packages, continuous monitoring — months of paperwork, unless it's automated." },
      { letter: "C", title: "Accessibility is law, not nice-to-have", body: "Section 508 / WCAG AA on day one — retrofitting is the expensive option." },
    ],
    approach: [
      { title: "Audit current estate", body: "Systems-of-record · authorization boundary · ATO status per system." },
      { title: "Stand up landing zones", body: "FedRAMP-aligned environment · evidence pipeline · accessibility gates in CI." },
      { title: "Migrate & modernize", body: "Reduce ATO scope as you go · retire what doesn't earn its keep." },
      { title: "Operate as one team", body: "Cleared engineers · cleared docs · runbooks your inspector general can read." },
    ],
    diagramLabel: "Authorization boundary on the perimeter · continuous monitoring threaded through · public-facing services accessible by default.",
    related: [
      { kind: "Solution", name: "Security & Compliance", href: "/solutions/security_compliance" },
      { kind: "Solution", name: "Hybrid Cloud", href: "/solutions/hybrid_cloud" },
      { kind: "Service", name: "Cloud Migration", href: "/services/cloud_migration" },
      { kind: "Service", name: "Cloud Strategy & Design", href: "/services/it_consulting" },
    ],
  },
  healthcare: {
    slug: "healthcare",
    name: "Healthcare",
    noun: "healthcare",
    heroImage: "/images/unsplash/photo-1576091160550-2173dba999ef-1600.webp",
    headline: { lead: "HIPAA-ready,", emph: "patient-first,", tail: "production-grade." },
    lede: "Payers, providers, and digital health — platforms that respect PHI, integrate with the EHR, and don't make clinicians fight the software.",
    pills: ["HIPAA", "HITRUST", "FHIR / HL7", "EHR-integrated"],
    challenges: [
      { letter: "A", title: "Integration with the EHR", body: "Epic, Cerner, Meditech — every shop different, every connection consequential. FHIR is the goal; HL7 v2 is the reality." },
      { letter: "B", title: "PHI that travels safely", body: "Encryption, key management, BAAs, minimum necessary — controls that audit cleanly across vendors." },
      { letter: "C", title: "Clinician experience", body: "If it adds a click, it doesn't ship. Workflows beat features, every time." },
    ],
    approach: [
      { title: "Audit current estate", body: "Data flows · BAAs · integration points · clinical workflows mapped." },
      { title: "Stand up landing zones", body: "HIPAA-aligned environment · key management · minimum-necessary access." },
      { title: "Migrate & modernize", body: "FHIR-first interfaces · safe parallel run with existing HL7 pipes." },
      { title: "Operate as one team", body: "On-call covering clinical hours · weekly review with informatics." },
    ],
    diagramLabel: "EHR on the left · patient services on the right · PHI flows encrypted, logged, and minimum-necessary throughout.",
    related: [
      { kind: "Solution", name: "Security & Compliance", href: "/solutions/security_compliance" },
      { kind: "Solution", name: "Data Analytics", href: "/solutions/data_analytics" },
      { kind: "Service", name: "AI & Machine Learning", href: "/services/ai_engineering" },
      { kind: "Service", name: "Software Development", href: "/services/software_development" },
    ],
  },
  logistics: {
    slug: "logistics",
    name: "Logistics",
    noun: "logistics & supply chain",
    heroImage: "/images/unsplash/photo-1586528116311-ad8dd3c8310d-1600.webp",
    headline: { lead: "Real-time fleets,", emph: "real-time", tail: "decisions." },
    lede: "Carriers, 3PLs, and shippers — telemetry at the edge, optimization in the cloud, dashboards in the dispatcher's hand.",
    pills: ["Real-time fleet", "TMS / WMS", "Edge telemetry"],
    challenges: [
      { letter: "A", title: "Edge that disconnects", body: "Trucks lose signal. Yards lose power. Platforms that can't survive that lose customers." },
      { letter: "B", title: "TMS / WMS integration sprawl", body: "Every customer wants a different EDI flavor and a different label format — without a one-off per integration." },
      { letter: "C", title: "Optimization in real time", body: "Routing, slotting, ETA — useful only if the decision reaches the driver before the next stop." },
    ],
    approach: [
      { title: "Audit current estate", body: "Fleet telemetry · TMS / WMS · EDI · customer integrations." },
      { title: "Stand up landing zones", body: "Edge fabric · real-time ingestion · canonical event model." },
      { title: "Migrate & modernize", body: "Streaming-first analytics · ML routing layered on top." },
      { title: "Operate as one team", body: "24/7 ops cover · holiday peak war-room with you." },
    ],
    diagramLabel: "Telemetry at the edge · streaming ingest in the middle · decisions and dashboards out to dispatchers and drivers.",
    related: [
      { kind: "Solution", name: "Data Analytics", href: "/solutions/data_analytics" },
      { kind: "Solution", name: "AI Automation", href: "/solutions/ai_automation" },
      { kind: "Service", name: "Software Development", href: "/services/software_development" },
      { kind: "Solution", name: "Hybrid Cloud", href: "/solutions/hybrid_cloud" },
    ],
  },
  manufacturing: {
    slug: "manufacturing",
    name: "Manufacturing",
    noun: "manufacturing",
    heroImage: "/images/unsplash/photo-1565793298595-6a879b1d9492-1600.webp",
    headline: { lead: "OT and IT,", emph: "finally", tail: "speaking." },
    lede: "Industrial IoT, MES, ERP, and the analytics layer that finally connects them. Plant-floor reality respected — boardroom dashboards that match it.",
    pills: ["Industrial IoT", "MES / ERP", "OT/IT bridge"],
    challenges: [
      { letter: "A", title: "OT/IT divide", body: "Plant systems and IT systems don't share vocabulary or risk tolerance. The architecture has to respect both." },
      { letter: "B", title: "Legacy protocols meet the cloud", body: "Modbus, Profinet, OPC UA, MQTT — all under one roof, none retiring soon." },
      { letter: "C", title: "Downtime is the only KPI", body: "Every roadmap loses to the line going down. Resilience first, features second." },
    ],
    approach: [
      { title: "Audit current estate", body: "Plant systems · OT network · MES · ERP · data flows." },
      { title: "Stand up landing zones", body: "Edge gateway pattern · OPC UA layer · cloud analytics environment." },
      { title: "Migrate & modernize", body: "Pilot one line · prove value · roll out plant by plant." },
      { title: "Operate as one team", body: "OT-aware on-call · change windows that respect production." },
    ],
    diagramLabel: "Plant floor on the bottom · OPC UA layer in the middle · ERP, analytics, and AI on top — gated, audited, observable.",
    related: [
      { kind: "Service", name: "AI & Machine Learning", href: "/services/ai_engineering" },
      { kind: "Solution", name: "Data Analytics", href: "/solutions/data_analytics" },
      { kind: "Solution", name: "Hybrid Cloud", href: "/solutions/hybrid_cloud" },
      { kind: "Service", name: "Cybersecurity", href: "/services/cybersecurity" },
    ],
  },
  retail: {
    slug: "retail",
    name: "Retail",
    noun: "retail",
    heroImage: "/images/unsplash/photo-1481437156560-3205f6a55735-1600.webp",
    headline: { lead: "Omnichannel,", emph: "actually.", tail: "" },
    lede: "Storefront, mobile, POS, and the warehouse behind them — one inventory, one customer view, one team holding the pager on Black Friday.",
    pills: ["Omnichannel", "Real-time inventory", "Peak-season ready"],
    challenges: [
      { letter: "A", title: "Peak demand on a calendar", body: "Black Friday, holiday weekends, drop days — capacity, latency, and ops all have to land on the same day." },
      { letter: "B", title: "Inventory truth", body: "Real-time, network-wide, accurate enough to promise on the PDP — even mid-rush." },
      { letter: "C", title: "Channel sprawl", body: "Web, app, store, marketplace · one customer · one identity · one carted state." },
    ],
    approach: [
      { title: "Audit current estate", body: "Storefront · OMS · WMS · POS · CDP — flows and failure modes." },
      { title: "Stand up landing zones", body: "Composable commerce baseline · CDN, identity, and observability live." },
      { title: "Migrate & modernize", body: "Headless front-end · real-time inventory layer · phased channel rollout." },
      { title: "Operate as one team", body: "Peak-season war-room with you · year-round on-call after." },
    ],
    diagramLabel: "Storefront and apps on top · OMS, inventory, and pricing in the middle · stores and warehouses at the base · one customer view threading through.",
    related: [
      { kind: "Service", name: "Software Development", href: "/services/software_development" },
      { kind: "Solution", name: "Data Analytics", href: "/solutions/data_analytics" },
      { kind: "Service", name: "Mobile Development", href: "/services/mobile_development" },
      { kind: "Solution", name: "AI Automation", href: "/solutions/ai_automation" },
    ],
  },
  telecom: {
    slug: "telecom",
    name: "Telecom",
    noun: "telecom",
    heroImage: "/images/unsplash/photo-1611605698335-8b1569810432-1600.webp",
    headline: { lead: "Carrier-grade —", emph: "without the carrier", tail: "timeline." },
    lede: "OSS / BSS modernization, 5G workloads, and the data plane behind them. Cloud-native patterns applied with telco-grade discipline.",
    pills: ["Carrier-grade", "5G ready", "OSS / BSS"],
    challenges: [
      { letter: "A", title: "OSS / BSS that calcified", body: "Decades of customizations, no clean seam. Modernization without freezing the business is the whole game." },
      { letter: "B", title: "Network functions in the cloud", body: "CNFs, service mesh, low-latency data plane — patterns the average platform team hasn't seen." },
      { letter: "C", title: "Reliability promises with teeth", body: "Five-nines isn't a slide — it's a regulator, a contract, and a board metric." },
    ],
    approach: [
      { title: "Audit current estate", body: "OSS · BSS · network functions · customer-facing channels." },
      { title: "Stand up landing zones", body: "Telco-grade baseline · low-latency networking · evidence pipeline." },
      { title: "Migrate & modernize", body: "Strangler around OSS/BSS · cloud-native CNFs in parallel." },
      { title: "Operate as one team", body: "NOC-adjacent on-call · runbooks that match your existing OSS." },
    ],
    diagramLabel: "OSS / BSS modernization on one side · CNF data plane on the other · observability and SLA reporting threading both.",
    related: [
      { kind: "Solution", name: "Kubernetes", href: "/solutions/kubernetes" },
      { kind: "Solution", name: "Hybrid Cloud", href: "/solutions/hybrid_cloud" },
      { kind: "Service", name: "DevOps & Automation", href: "/services/devops_automation" },
      { kind: "Service", name: "Cybersecurity", href: "/services/cybersecurity" },
    ],
  },
};
